# シフトポジション
ShiftPosition shift_position

# 前輪舵角
RudderAngle rudder_angle_front

# 後輪舵角
RudderAngle rudder_angle_rear

# ブレーキ状態
BrakeState brake_state

# 補助ブレーキ状態
AuxiliaryBrakeState auxiliary_brake_state

# アクセルペダル開度
ThrottlePosition throttle_position

# 灯火の状態
ExteriorLights exterior_lights

# 各種のシステムの作動状態
VehicleControlSystemStates control_system_states

# 車両用途種別
VehicleRole role

# 車両用途種別毎の状態
VehicleExtendedInformation extended_info

# 牽引車両
ObjectId towing_vehicle_id
