# フリースペース ID
dm_object_info_msgs/ObjectId id

# 情報取得時刻
dm_object_info_msgs/GeneratedTime time

# 存在信頼度
dm_object_info_msgs/Existency existency

# 検知漏れ物標サイズ
dm_object_info_msgs/ObjectLength missing_detection_size

# 始点位置
dm_object_info_msgs/ObjectPosition position_flont

# 終点位置
dm_object_info_msgs/ObjectPosition position_rear

# 長さ
dm_object_info_msgs/ObjectLengthWithConfidence length

# 始点物標 ID
dm_object_info_msgs/ObjectId id_start

# 終点物標 ID
dm_object_info_msgs/ObjectId id_end

# 情報源のリス
dm_object_info_msgs/ObjectId[] information_source_list
