# フリースペース ID
dm_object_info_msgs/ObjectId id

# 情報取得時刻
dm_object_info_msgs/TimestampIts time

# 存在信頼度
dm_object_info_msgs/ExistenceConfidence existency

# 検知漏れ物標サイズ
dm_object_info_msgs/ObjectDimensionValue minimal_detectable_size

# 始点位置
dm_object_info_msgs/Location position_begin

# 終点位置
dm_object_info_msgs/Location position_end

# 長さ
dm_object_info_msgs/ObjectDimension length

# 始点物標 ID
dm_object_info_msgs/ObjectId id_begin

# 終点物標 ID
dm_object_info_msgs/ObjectId id_end

# 情報源のリス
dm_object_info_msgs/ObjectId[] information_source_list
